// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.19.4
// source: internal/vnextconnector/agentcontrolv1/agent_control.proto

package agentcontrolv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConnectorEnrollment_EnrollConnector_FullMethodName = "/dirextalk.agent_control.v1.ConnectorEnrollment/EnrollConnector"
)

// ConnectorEnrollmentClient is the client API for ConnectorEnrollment service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Agent Control is connector-initiated and outbound-only. ConnectorEnrollment
// is mounted only on the ordinary server-authenticated TLS listener;
// ConnectorControl is mounted only on the listener that requires the exact
// per-Connector mTLS identity from ADR-0005. Keeping separate services makes
// the transport trust boundary explicit rather than relying on handler checks.
//
// Every request, response, ClientFrame, and ServerFrame is capped at 262144
// encoded bytes. Implementations reject a frame with no known oneof member.
// String limits are UTF-8 byte limits and strings reject C0/C1 controls. All
// uint64 counters and millisecond timestamps are limited to
// 0..9007199254740991; fields documented as positive reject zero.
//
// Cross-language signatures and digests use this exact framing:
//
//	LP(x) = U64BE(byte_length(x)) || x
//	COMMIT(domain, parts...) = SHA-256(LP(ASCII(domain)) || LP(part1) || ...)
//
// UUID parts are the 16 RFC 4122 network-order bytes parsed from canonical
// text; integer parts are their unsigned eight-byte big-endian representation.
// The raw enrollment-token digest uses domain
// "dirextalk.connector-enrollment-token.v1" and the token as its only part.
//
// Enrollment signatures cover LP("dirextalk.connector-enrollment-proof.v1")
// followed by LP of, in order: tenant UUID, host UUID, Connector UUID,
// generation U64BE, spec revision U64BE, request UUID, token digest, control
// public key, and refresh public key. request_digest uses COMMIT domain
// "dirextalk.connector-enrollment-request.v1" with the complete signing
// transcript, control signature, and refresh signature as its three parts.
//
// Rotation signatures cover LP(
// "dirextalk.connector-credential-rotation-proof.v1") followed by LP of, in
// order: tenant UUID, Connector UUID, request UUID, authenticated current
// credential UUID, current generation U64BE, successor generation U64BE,
// command sequence U64BE, command payload digest, successor revision U64BE,
// rotation nonce, and new control public key. successor generation is exactly
// current generation + 1. request_digest uses COMMIT domain
// "dirextalk.connector-credential-rotation-request.v1" with the complete
// signing transcript, current refresh signature, and new control signature.
//
// A credential result digest uses COMMIT domain
// "dirextalk.connector-credential-result.v1" with, in order: credential UUID,
// tenant UUID, Connector UUID, generation U64BE, credential revision U64BE,
// control public key, refresh public key, leaf fingerprint, certificate count
// U64BE, each leaf-first DER certificate as its own part, valid-from U64BE, and
// valid-until U64BE. Command payload digests use COMMIT domain
// "dirextalk.connector-command-payload.v1" with the exact selected oneof
// submessage bytes as the only part. Encoded-command digests use COMMIT domain
// "dirextalk.connector-encoded-command.v1" with the complete encoded
// DurableCommand bytes as the only part.
type ConnectorEnrollmentClient interface {
	EnrollConnector(ctx context.Context, in *EnrollConnectorRequest, opts ...grpc.CallOption) (*EnrollConnectorResponse, error)
}

type connectorEnrollmentClient struct {
	cc grpc.ClientConnInterface
}

func NewConnectorEnrollmentClient(cc grpc.ClientConnInterface) ConnectorEnrollmentClient {
	return &connectorEnrollmentClient{cc}
}

func (c *connectorEnrollmentClient) EnrollConnector(ctx context.Context, in *EnrollConnectorRequest, opts ...grpc.CallOption) (*EnrollConnectorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnrollConnectorResponse)
	err := c.cc.Invoke(ctx, ConnectorEnrollment_EnrollConnector_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConnectorEnrollmentServer is the server API for ConnectorEnrollment service.
// All implementations must embed UnimplementedConnectorEnrollmentServer
// for forward compatibility.
//
// Agent Control is connector-initiated and outbound-only. ConnectorEnrollment
// is mounted only on the ordinary server-authenticated TLS listener;
// ConnectorControl is mounted only on the listener that requires the exact
// per-Connector mTLS identity from ADR-0005. Keeping separate services makes
// the transport trust boundary explicit rather than relying on handler checks.
//
// Every request, response, ClientFrame, and ServerFrame is capped at 262144
// encoded bytes. Implementations reject a frame with no known oneof member.
// String limits are UTF-8 byte limits and strings reject C0/C1 controls. All
// uint64 counters and millisecond timestamps are limited to
// 0..9007199254740991; fields documented as positive reject zero.
//
// Cross-language signatures and digests use this exact framing:
//
//	LP(x) = U64BE(byte_length(x)) || x
//	COMMIT(domain, parts...) = SHA-256(LP(ASCII(domain)) || LP(part1) || ...)
//
// UUID parts are the 16 RFC 4122 network-order bytes parsed from canonical
// text; integer parts are their unsigned eight-byte big-endian representation.
// The raw enrollment-token digest uses domain
// "dirextalk.connector-enrollment-token.v1" and the token as its only part.
//
// Enrollment signatures cover LP("dirextalk.connector-enrollment-proof.v1")
// followed by LP of, in order: tenant UUID, host UUID, Connector UUID,
// generation U64BE, spec revision U64BE, request UUID, token digest, control
// public key, and refresh public key. request_digest uses COMMIT domain
// "dirextalk.connector-enrollment-request.v1" with the complete signing
// transcript, control signature, and refresh signature as its three parts.
//
// Rotation signatures cover LP(
// "dirextalk.connector-credential-rotation-proof.v1") followed by LP of, in
// order: tenant UUID, Connector UUID, request UUID, authenticated current
// credential UUID, current generation U64BE, successor generation U64BE,
// command sequence U64BE, command payload digest, successor revision U64BE,
// rotation nonce, and new control public key. successor generation is exactly
// current generation + 1. request_digest uses COMMIT domain
// "dirextalk.connector-credential-rotation-request.v1" with the complete
// signing transcript, current refresh signature, and new control signature.
//
// A credential result digest uses COMMIT domain
// "dirextalk.connector-credential-result.v1" with, in order: credential UUID,
// tenant UUID, Connector UUID, generation U64BE, credential revision U64BE,
// control public key, refresh public key, leaf fingerprint, certificate count
// U64BE, each leaf-first DER certificate as its own part, valid-from U64BE, and
// valid-until U64BE. Command payload digests use COMMIT domain
// "dirextalk.connector-command-payload.v1" with the exact selected oneof
// submessage bytes as the only part. Encoded-command digests use COMMIT domain
// "dirextalk.connector-encoded-command.v1" with the complete encoded
// DurableCommand bytes as the only part.
type ConnectorEnrollmentServer interface {
	EnrollConnector(context.Context, *EnrollConnectorRequest) (*EnrollConnectorResponse, error)
	mustEmbedUnimplementedConnectorEnrollmentServer()
}

// UnimplementedConnectorEnrollmentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConnectorEnrollmentServer struct{}

func (UnimplementedConnectorEnrollmentServer) EnrollConnector(context.Context, *EnrollConnectorRequest) (*EnrollConnectorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnrollConnector not implemented")
}
func (UnimplementedConnectorEnrollmentServer) mustEmbedUnimplementedConnectorEnrollmentServer() {}
func (UnimplementedConnectorEnrollmentServer) testEmbeddedByValue()                             {}

// UnsafeConnectorEnrollmentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConnectorEnrollmentServer will
// result in compilation errors.
type UnsafeConnectorEnrollmentServer interface {
	mustEmbedUnimplementedConnectorEnrollmentServer()
}

func RegisterConnectorEnrollmentServer(s grpc.ServiceRegistrar, srv ConnectorEnrollmentServer) {
	// If the following call panics, it indicates UnimplementedConnectorEnrollmentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConnectorEnrollment_ServiceDesc, srv)
}

func _ConnectorEnrollment_EnrollConnector_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnrollConnectorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectorEnrollmentServer).EnrollConnector(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectorEnrollment_EnrollConnector_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectorEnrollmentServer).EnrollConnector(ctx, req.(*EnrollConnectorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ConnectorEnrollment_ServiceDesc is the grpc.ServiceDesc for ConnectorEnrollment service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConnectorEnrollment_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dirextalk.agent_control.v1.ConnectorEnrollment",
	HandlerType: (*ConnectorEnrollmentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EnrollConnector",
			Handler:    _ConnectorEnrollment_EnrollConnector_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/vnextconnector/agentcontrolv1/agent_control.proto",
}

const (
	ConnectorControl_Control_FullMethodName = "/dirextalk.agent_control.v1.ConnectorControl/Control"
)

// ConnectorControlClient is the client API for ConnectorControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConnectorControlClient interface {
	Control(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientFrame, ServerFrame], error)
}

type connectorControlClient struct {
	cc grpc.ClientConnInterface
}

func NewConnectorControlClient(cc grpc.ClientConnInterface) ConnectorControlClient {
	return &connectorControlClient{cc}
}

func (c *connectorControlClient) Control(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientFrame, ServerFrame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ConnectorControl_ServiceDesc.Streams[0], ConnectorControl_Control_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ClientFrame, ServerFrame]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConnectorControl_ControlClient = grpc.BidiStreamingClient[ClientFrame, ServerFrame]

// ConnectorControlServer is the server API for ConnectorControl service.
// All implementations must embed UnimplementedConnectorControlServer
// for forward compatibility.
type ConnectorControlServer interface {
	Control(grpc.BidiStreamingServer[ClientFrame, ServerFrame]) error
	mustEmbedUnimplementedConnectorControlServer()
}

// UnimplementedConnectorControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConnectorControlServer struct{}

func (UnimplementedConnectorControlServer) Control(grpc.BidiStreamingServer[ClientFrame, ServerFrame]) error {
	return status.Error(codes.Unimplemented, "method Control not implemented")
}
func (UnimplementedConnectorControlServer) mustEmbedUnimplementedConnectorControlServer() {}
func (UnimplementedConnectorControlServer) testEmbeddedByValue()                          {}

// UnsafeConnectorControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConnectorControlServer will
// result in compilation errors.
type UnsafeConnectorControlServer interface {
	mustEmbedUnimplementedConnectorControlServer()
}

func RegisterConnectorControlServer(s grpc.ServiceRegistrar, srv ConnectorControlServer) {
	// If the following call panics, it indicates UnimplementedConnectorControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConnectorControl_ServiceDesc, srv)
}

func _ConnectorControl_Control_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ConnectorControlServer).Control(&grpc.GenericServerStream[ClientFrame, ServerFrame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConnectorControl_ControlServer = grpc.BidiStreamingServer[ClientFrame, ServerFrame]

// ConnectorControl_ServiceDesc is the grpc.ServiceDesc for ConnectorControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConnectorControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dirextalk.agent_control.v1.ConnectorControl",
	HandlerType: (*ConnectorControlServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Control",
			Handler:       _ConnectorControl_Control_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "internal/vnextconnector/agentcontrolv1/agent_control.proto",
}
